# Generated by Django 5.0.6 on 2024-06-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('availability_status', models.CharField(choices=[('NA', 'Not Available'), ('A', 'Available'), ('L', 'Lent'), ('R', 'Reserved'), ('Up', 'Upcoming')], max_length=5)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='libmanage.authordetails')),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='libmanage.genre')),
            ],
        ),
    ]
